# Generated by Django 5.1.3 on 2024-12-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(max_length=100)),
                ('recipient_username', models.CharField(max_length=100)),
                ('decrypted_message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='receiver_attachments/')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'receiverapp_message',
            },
        ),
    ]
