# Generated by Django 5.1.4 on 2024-12-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendermessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20),
        ),
    ]
