# Generated by Django 5.1.4 on 2024-12-25 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0001_initial'),
        ('SenderApp', '0002_alter_sendermessage_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='CommonApp.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
